router:
  port: 9090

chain:
  rpc: http://106.13.236.225
  port: 8898
  contract:
    address: 0x6E8E1Cc8f3e01A1bE56D5a0B1Fba136fcDE33832

mysql:
  host: 106.13.236.225
  port: 3303
  user: LDJL
  passwd: huangjg@1001
  database: DABC

redis:
  host: 106.13.236.225
  port: 6379
  password: huangjg
  db: 0

email:
  host: smtp.163.com
  port: 465
  user: huang_learn@163.com
  pwd: XUIJDSDUJRHPJPEH

auth:
  salt: the dabc salt
  signkey: askjdfhasldkfjlkajsdf


